#!/bin/bash -x
###############################################################################
#
# Shell functions to process data from supernovas images.
#
###############################################################################
flat_base_name="FFF_"
dark_base_name="CDO_"
galaxy_base_name="GLX_"
supernova_base_name="GSN_"
siril_script="sn_siril.ssf"

function info() {

    echo "Process files obtained in supernova group."

}

###############################################################################
# $1: exposition in seconds
# $2: darks folder
# $3: tmp dir where to save stacked frame
# $4: stack_name
###############################################################################
function generate_dark_frame() {

    exposition=${1}
    dark_src_folder=${2}
    tmp_dir=${3}
    dark_exposition_base_name="${dark_base_name}${exposition}S_"
    stack_name=${4}.fit
    
    for source_file in `find ${dark_src_folder} -name "${dark_exposition_base_name}*" -type f`;
    do
        cp ${source_file} ${siril_tmp_dir}/${tmp_dir}        
    done

    echo "cd $tmp_dir" >> ${siril_tmp_dir}/${siril_script}  
    echo "stack ${dark_exposition_base_name} rej 3 3 -nonorm -out=${stack_name}" >> ${siril_tmp_dir}/${siril_script}
    echo "cd .." >> ${siril_tmp_dir}/${siril_script}

}


###############################################################################
# $1: exposition in seconds
# $2: flats folder
# $3: filter: R,DS
# $4: tmp dir where to save stacked frame
# $5: stack_name
###############################################################################
function generate_flat_frame() {

    exposition=${1}
    flat_src_folder=${2}
    filter=${3}
    tmp_dir=${4}
    flat_exposition_base_name="${flat_base_name}${exposition}S_"
    stack_name=${5}_${filter}.fit
    
    for source_file in `find ${flat_src_folder} -name "${flat_exposition_base_name}*" -type f`;
    do
        cp ${source_file} ${siril_tmp_dir}/${tmp_dir}        
    done

    echo "cd $tmp_dir" >> ${siril_tmp_dir}/${siril_script}  
    echo "stack ${flat_exposition_base_name} rej 3 3 -nonorm -out=${stack_name}" >> ${siril_tmp_dir}/${siril_script}
    echo "cd .." >> ${siril_tmp_dir}/${siril_script}

}


siril_tmp_dir="./siril_process"
echo "Creating ${siril_tmp_dir} folder for processing"
mkdir ${siril_tmp_dir}


echo "#############################" >  ${siril_tmp_dir}/${siril_script}
echo "# Autogenerated siril process" >>  ${siril_tmp_dir}/${siril_script}
echo "#############################" >>  ${siril_tmp_dir}/${siril_script}


echo "Creating ${siril_tmp_dir}/darkflats folder for processing"
mkdir ${siril_tmp_dir}/darkflats

echo "Creating ${siril_tmp_dir}/flats folder for processing"
mkdir ${siril_tmp_dir}/flats

echo "Creating ${siril_tmp_dir}/darks folder for processing"
mkdir ${siril_tmp_dir}/darks

echo "Generating dark flats "
generate_dark_frame 5 ${1} darkflats darkflat

echo "Generating R flats "
generate_flat_frame 5 ${1} R flats flat

echo "Generating DS flats "
generate_flat_frame 5 ${1} R flats flat

echo "Generating darks "
generate_dark_frame 60 ${1} darks darks